name: Build sqlite artifact

on:
  workflow_call:
    inputs:
      ref:
        description: "git ref"
        type: string
        default: master

jobs:
  build:
    name: "Build sqlite.wasm"
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/sqlite
          ref: ${{ inputs.ref }}

      - name: Setup wasi-sdk
        run: |
          curl -L https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-15/wasi-sdk-15.0-linux.tar.gz | tar xz -C ./
          mv wasi-sdk-* wasi-sdk

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Download marine artifact
        id: marine
        uses: actions/download-artifact@v3
        continue-on-error: true
        with:
          name: marine
          path: ~/.local/bin

      - name: Make marine executable
        if: steps.marine.outcome == 'success'
        run: chmod +x ~/.local/bin/marine

      - name: Setup marine
        if: steps.marine.outcome == 'failure'
        uses: fluencelabs/setup-marine@v1

      - name: Build sqlite-wasm
        run: make

      - name: Upload sqlite-wasm
        uses: actions/upload-artifact@v3
        with:
          name: sqlite-wasm
          path: sqlite3.wasm
          if-no-files-found: error
