name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
      - "!.github/workflows/build.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
      - "!.github/workflows/build.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: "sqlite"
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ github.ref }}

  snapshot:
    needs: build
    name: "sqlite-wasm"
    uses: fluencelabs/sqlite-wasm-connector/.github/workflows/snapshot.yml@master

  spell:
    needs:
      - snapshot
    uses: fluencelabs/spell/.github/workflows/snapshot.yml@main
    with:
      cargo-dependencies: |
        [
          {
            "package": "marine-sqlite-connector",
            "version": "=${{ needs.snapshot.outputs.version }}",
            "registry": "fluence"
          }
        ]

  nox:
    needs:
      - spell

    uses: fluencelabs/nox/.github/workflows/build.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.spell.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.spell.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  nox-snapshot:
    name: "nox"
    needs:
      - nox

    uses: fluencelabs/nox/.github/workflows/container.yml@master
    with:
      image-name: "docker.fluence.dev/sqlite-wasm-connector"
      flavour: "minimal"

  spell-aqua-tests:
    name: "spell"
    needs:
      - nox-snapshot
    uses: fluencelabs/spell/.github/workflows/tests.yml@main
    with:
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"

  registry:
    needs:
      - snapshot
      - nox-snapshot
    uses: fluencelabs/registry/.github/workflows/tests.yml@main
    with:
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"
      cargo-dependencies: |
        [
          {
            "package": "marine-sqlite-connector",
            "version": "=${{ needs.snapshot.outputs.version }}",
            "registry": "fluence"
          }
        ]
