name: "release"

on:
  push:
    branches:
      - "master"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      release-created: ${{ steps.release.outputs['release_created'] }}
      tag-name: ${{ steps.release.outputs['tag_name'] }}
      version: ${{ steps.release.outputs['version'] }}
      pr: ${{ steps.release.outputs['pr'] }}

    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }}
          command: manifest
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        if: steps.release.outputs.releases_created
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq

  build:
    if: needs.release-please.outputs.release-created
    needs: release-please
    uses: ./.github/workflows/build.yml

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-please
      - build

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download sqlite-wasm
        uses: actions/download-artifact@v3
        with:
          name: sqlite-wasm
          path: artifacts/

      - name: Create archive
        run: tar caf artifacts/sqlite3.tar.gz -C ./artifacts/ sqlite3.wasm -C ../.github/misc/ module.yaml

      - name: Generate checksums
        id: sum
        run: |
          sha256sum * | tee > sqlite3_SHA256_SUMS
        working-directory: artifacts

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/*
          tag_name: ${{ needs.release-please.outputs.tag-name }}
